### ISSUE TITLE
DRY up HTML

### ISSUE THREAD

**Issue by scascketta** [KhalidGit/psibeta#5]
We have a lot of repetition in our HTML files for the head, navbar, and footer. If we were writing a dynamic application, it'd be easy to avoid this by using a framework's templating engine (like Jinja2), however this is static.

I think our best bet is to use [HTML Imports](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) as decreed by the [W3C](http://w3c.github.io/webcomponents/spec/imports/). All the other solutions seem a little hacky, and hard to understand for newbs. Using the [polyfill](http://www.polymer-project.org/platform/html-imports.html) from the Polymer team should solve compatibility issues.

**Comment by yparekh39** [comment]
Yeah, I agree.

**Comment by scascketta** [comment]
Problematic for the time being on Firefox. It seems that even with the Polymer polyfill, Firefox can't import content from import elements.
